server {
	listen 80;
	server_name audiobookshelf.local;
	return 301 https://audiobookshelf.local$request_uri;
}

server {
	listen 443 ssl;
	server_name audiobookshelf.local;
	ssl_certificate		/etc/nginx/ssl/audiobookshelf-selfsigned.crt;
	ssl_certificate_key	/etc/nginx/ssl/audiobookshelf-selfsigned.key;

	location / {
		proxy_pass http://localhost:13378;
	}
}
